try {
  var a = 2;
  console.log(2);
} catch {}

const test = () => {};
